### ISSUE TITLE
Duplicate symbols

### ISSUE THREAD

**Issue by hriener** [msoeken/header-only-sat#2]
Having a header-only SAT-solver is a nice idea!

However, as far as I can tell, in order to make this idea work you have to inline all methods in `Solver.cc`. Otherwise, when you build multiple C++ files, e.g., with our current testing approach, you will end up with duplicate symbols when linking them together.

**Comment by msoeken** [comment]
True, that is a crucial issue. I'll try to address this problem with a patch.

**Comment by hriener** [comment]
PR #3 solves the problem for me.
